---
- name: Prepare Docker for a GitLab server
  hosts: gitlab_servers
  become: true
  tasks:
  - name: Install aptitude latest
    apt:
      state: latest
      update_cache: true

  - name: Check uninstall older docker versions
    apt:
      pkg:
        - docker
        - docker-engine
        - docker.io
        - containerd
        - runc
      state: absent

  - name: Install required system dependency packages
    apt:
      pkg:
        - ca-certificates
        - curl
        - gnupg
      state: latest
      update_cache: true

  - name: Add Docker's official GPG apt key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Set up Docker repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu focal stable

  - name: Update aptitude index
    apt:
      state: latest
      update_cache: true

  - name: Install Docker
    apt:
      pkg:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
      state: latest
      update_cache: true
